# Generated by Django 3.1.7 on 2021-08-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='extraData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
