# Generated by Django 3.1.7 on 2021-03-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(0, 'TEXT'), (1, 'LOCATION'), (2, 'PHOTO')], default=0),
        ),
    ]
